name: codecov

on: [push]

jobs:
  phpunit:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - 7.4
    env:
      extensions: openssl, swoole, posix
      key: cache-v1 # can be any string, change to clear the extension cache.
    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: pecl
          extensions: ${{ env.extensions }}
          # coverage: xdebug #optional, setup coverage driver
          ini-values: pcov.directory=., pcov.exclude="~vendor~"
          coverage: pcov #optional, setup coverage driver

      - name: Check Version
        run: |
          php -v
          php -m
          composer -V

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies (composer.lock)
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: composer exec -- phpunit --coverage-clover=coverage.xml -v

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          file: ./coverage.xml #optional
          flags: unittests #optional
          name: codecov-umbrella #optional
